let words = [
  // {"thought"    : "فكرة" },
  // {"military"   : "عسكر" },
  // {"courage"    : "شجاع" },
  // {"prime"      : "رئيس" },
  // {"minister"   : "وزير" },
  // {"hunt"       : "يطارد"},
  // {"religion"   : "دين"  },
  // {"resolution" : "قرار" },
  // {"seek"       : "يسعى" },
  // {"joy"        : "فرح"  },
  // {"lasting"    : "دائم" },
  // {"terrible"   : "فظيع" },
  // {"climate"    : "مناخ" },
  // {"habit"      : "عادة" },
  // {"gratitude"  : "شكر"  },
  // {"journal"    : "دفتر" },
  // {"attend"     : "يحضر" },
  // {"urge"       : "يحث"  },
  // ====================
  {"persuade"        : "يقنع"         },
  {"Sacrifice"       : "يضحي"         },
  {"emotion"         : "مشاعر"      },
  {"ethic"           : "أخلاق"        },
  {"falling short"   : "تقصير"      },
  {"Quiet"           : "هادئ"         },
  {"Quite"           : "تماما"        },
  {"Quit"            : "يخرج"         },
  {"judge"           : "قاضي"       },
  {"Competition"     : "منافسة"     },
  {"Specialist"      : "متخصص"        },
  {"Surgery"         : "عملية جراحية"},
  {"mental disorder" : "اضطراب عقلي" },
  {"hopeless"        : "ميؤوس منه"   },
  {"Useless"         : "عديم فائدة"},
  {"Criticize"       : "ينتقد"       },
  {"husband"         : "زوج"       },
  {"dish"            : "طبق"       },
  {"arm"             : "ذراع او سلاح" },
  {"shoulder"        : "كتف"         },
  {"expect"          : "يتوقع"       },
  {"except"          : "ما عدا"      },
  {"magazine"        : "مجلة"        },
  {"overly"          : "مفرط"        },
  {"depression"      : "كآبة"        },
  {"alcohol"         : "خمور"      },
  {"drugs"           : "مخدرات"    },
  {"suicide"         : "انتحار"      },
  {"overcome"        : "يتغلب على"   },
  {"Christian"       : "مسيحي"       },
  {"faith"           : "إيمان"     },
  {"willing"         : "مستعد"       },
  // ====================
];